pip3 install argon2-cffi==23.1.0 --break-system-packages
pip3 install argon2-cffi-bindings==21.2.0 --break-system-packages
pip3 install argparse==1.4.0 --break-system-packages 
pip3 install arrow==1.3.0 --break-system-packages 
pip3 install async-lru==2.0.4 --break-system-packages 
pip3 install attrs==23.2.0 --break-system-packages 
pip3 install babel==2.15.0 --break-system-packages 
pip3 install beautifulsoup4==4.12.3 --break-system-packages 
pip3 install bleach==6.1.0 --break-system-packages 
pip3 install certifi==2024.6.2 --break-system-packages 
pip3 install cffi==1.16.0 --break-system-packages 
pip3 install charset-normalizer==3.3.2 --break-system-packages 
pip3 install click==8.1.7 --break-system-packages 
pip3 install click-plugins==1.1.1 --break-system-packages 
pip3 install cligj==0.7.2 --break-system-packages 
pip3 install cmake==3.29.6 --break-system-packages 
pip3 install contourpy==1.2.1 --break-system-packages 
pip3 install cycler==0.12.1 --break-system-packages 
pip3 install decorator==5.1.1 --break-system-packages 
pip3 install defusedxml==0.7.1 --break-system-packages 
pip3 install docker-pycreds==0.4.0 --break-system-packages 
pip3 install fastjsonschema==2.20.0 --break-system-packages 
pip3 install fonttools==4.53.0 --break-system-packages 
pip3 install fqdn==1.5.1 --break-system-packages 
pip3 install fsspec==2024.6.1 --break-system-packages 
pip3 install gitdb==4.0.11 --break-system-packages 
pip3 install gitpython==3.1.43 --break-system-packages 
pip3 install h11==0.14.0 --break-system-packages 
pip3 install httpcore==1.0.5 --break-system-packages 
pip3 install httpx==0.27.0 --break-system-packages 
pip3 install huggingface-hub==0.23.4 --break-system-packages 
pip3 install idna==3.7 --break-system-packages 
pip3 install imagecodecs==2024.6.1 --break-system-packages 
pip3 install ipywidgets==8.1.3 --break-system-packages 
pip3 install isoduration==20.11.0 --break-system-packages 
pip3 install jinja2==3.1.4 --break-system-packages 
pip3 install joblib==1.4.2 --break-system-packages 
pip3 install json5==0.9.25 --break-system-packages 
pip3 install jsonpointer==3.0.0 --break-system-packages 
pip3 install jsonschema==4.22.0 --break-system-packages 
pip3 install jsonschema-specifications==2023.12.1 --break-system-packages 
pip3 install jupyter==1.0.0 --break-system-packages 
pip3 install jupyter-console==6.6.3 --break-system-packages 
pip3 install jupyter-events==0.10.0 --break-system-packages 
pip3 install jupyter-lsp==2.2.5 --break-system-packages 
pip3 install jupyter-server==2.14.1 --break-system-packages 
pip3 install jupyter-server-terminals==0.5.3 --break-system-packages 
pip3 install jupyterlab==4.2.3 --break-system-packages 
pip3 install jupyterlab-pygments==0.3.0 --break-system-packages 
pip3 install jupyterlab-server==2.27.2 --break-system-packages 
pip3 install jupyterlab-widgets==3.0.11 --break-system-packages 
pip3 install kiwisolver==1.4.5 --break-system-packages 
pip3 install lit==18.1.8 --break-system-packages 
pip3 install markupsafe==2.1.5 --break-system-packages 
pip3 install matplotlib==3.9.0 --break-system-packages 
pip3 install mistune==3.0.2 --break-system-packages 
pip3 install mpmath==1.3.0 --break-system-packages 
pip3 install nbclient==0.10.0 --break-system-packages 
pip3 install nbconvert==7.16.4 --break-system-packages 
pip3 install nbformat==5.10.4 --break-system-packages 
pip3 install notebook==7.2.1 --break-system-packages 
pip3 install notebook-shim==0.2.4 --break-system-packages 
pip3 install nvidia-cublas-cu11==11.10.3.66 --break-system-packages 
pip3 install nvidia-cuda-cupti-cu11==11.7.101 --break-system-packages 
pip3 install nvidia-cuda-nvrtc-cu11==11.7.99 --break-system-packages 
pip3 install nvidia-cuda-runtime-cu11==11.7.99 --break-system-packages 
pip3 install nvidia-cudnn-cu11==8.5.0.96 --break-system-packages 
pip3 install nvidia-curand-cu11==10.2.10.91 --break-system-packages 
pip3 install nvidia-cusolver-cu11==11.4.0.1 --break-system-packages 
pip3 install nvidia-cusparse-cu11==11.7.4.91 --break-system-packages 
pip3 install nvidia-nccl-cu11==2.14.3 --break-system-packages 
pip3 install nvidia-nvtx-cu11==11.7.91 --break-system-packages 
pip3 install overrides==7.7.0 --break-system-packages 
pip3 install packaging==24.1 --break-system-packages 
pip3 install pandas==2.2.2 --break-system-packages 
pip3 install pandocfilters==1.5.1 --break-system-packages 
pip3 install pexpect==4.9.0 --break-system-packages 
pip3 install pillow==10.4.0 --break-system-packages 
pip3 install prometheus-client==0.20.0 --break-system-packages 
pip3 install psutil==6.0.0 --break-system-packages 
pip3 install ptyprocess==0.7.0 --break-system-packages 
pip3 install pycparser==2.22 --break-system-packages 
pip3 install pygments==2.18.0 --break-system-packages 
pip3 install pyparsing==3.1.2 --break-system-packages 
pip3 install python-json-logger==2.0.7 --break-system-packages 
pip3 install pytz==2024.1 --break-system-packages 
pip3 install pyyaml==6.0.1 --break-system-packages 
pip3 install qtconsole==5.5.2 --break-system-packages 
pip3 install qtpy==2.4.1 --break-system-packages 
pip3 install rasterio==1.3.10 --break-system-packages 
pip3 install referencing==0.35.1 --break-system-packages 
pip3 install regex==2024.5.15 --break-system-packages 
pip3 install requests==2.32.3 --break-system-packages 
pip3 install rfc3339-validator==0.1.4 --break-system-packages 
pip3 install rfc3986-validator==0.1.1 --break-system-packages 
pip3 install rpds-py==0.18.1 --break-system-packages 
pip3 install safetensors==0.4.3 --break-system-packages 
pip3 install scikit-learn==1.5.1 --break-system-packages 
pip3 install scipy==1.14.0 --break-system-packages 
pip3 install send2trash==1.8.3 --break-system-packages 
pip3 install sentry-sdk==2.7.1 --break-system-packages 
pip3 install setproctitle==1.3.3 --break-system-packages 
pip3 install six==1.16.0 --break-system-packages 
pip3 install smmap==5.0.1 --break-system-packages 
pip3 install sniffio==1.3.1 --break-system-packages 
pip3 install snuggs==1.4.7 --break-system-packages 
pip3 install soupsieve==2.5 --break-system-packages 
pip3 install sympy==1.12.1 --break-system-packages 
pip3 install terminado==0.18.1 --break-system-packages 
pip3 install threadpoolctl==3.5.0 --break-system-packages 
pip3 install tifffile==2024.7.2 --break-system-packages 
pip3 install tinycss2==1.3.0 --break-system-packages 
pip3 install tokenizers==0.19.1 --break-system-packages 
pip3 install tomli==2.0.1 --break-system-packages 
pip3 install torch==2.0.1 --break-system-packages 
pip3 install torchaudio==2.0.2 --break-system-packages 
pip3 install torchvision==0.15.2 --break-system-packages 
pip3 install tqdm==4.66.4 --break-system-packages 
pip3 install transformers==4.42.3 --break-system-packages 
pip3 install triton==2.0.0 --break-system-packages 
pip3 install types-python-dateutil==2.9.0.20240316 --break-system-packages 
pip3 install tzdata==2024.1 --break-system-packages 
pip3 install uri-template==1.3.0 --break-system-packages 
pip3 install urllib3==2.2.2 --break-system-packages 
pip3 install wandb==0.17.3 --break-system-packages 
pip3 install webcolors==24.6.0 --break-system-packages 
pip3 install webencodings==0.5.1 --break-system-packages 
pip3 install websocket-client==1.8.0 --break-system-packages 
pip3 install widgetsnbextension==4.0.11 --break-system-packages 
pip3 install yacs==0.1.8
